kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-hpa
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-contaier
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100
              memory: 124Mi


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx

  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
