apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # - ../../base/service.yaml
  # - ../../base/deployment.yaml
namespace: dev
namePrefix: dev-
images:
  - name: rk0617/nodeapp-demo1
    newTag: v1.1.0

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nodeapp-demo1-deployment
    
 