apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: pv-namespace
spec:
  resources:
    requests:
      storage: 15Gi
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
